server:
  port: 8080
#  forward-headers-strategy: framework

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: artist-service
          uri: lb://artist-service
          predicates:
            - Path=/artist/**
          filters:
            - RewritePath=/artist/(?<path>.*), /$\{path}
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/song/**
          filters:
            - RewritePath=/song/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
spring-doc:
  swagger-ui:
    urls:
      - name: artist
        url: /v3/api-docs/artist
      - name: song
        url: /v3/api-docs/song


