server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: artist-service
          uri: lb://artist-service
          predicates:
            - Path=/artist/**
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/song/**



