spring:
  datasource:
    url: jdbc:mysql://localhost:3306/artist_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
    name: security-service

server:
  port: 8888