server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/LauraGullo/Artist_microservice
          search-paths: config-data


  application:
    name: config-service